### ISSUE TITLE
Remove console usage

### ISSUE THREAD

**Issue by satazor** [bahmutov/bin-up#4]
console.error is being used here https://github.com/bahmutov/bin-up/blob/master/src/index.js#L33 and in some other places.

Could we replace those with https://nodejs.org/api/util.html#util_util_debuglog_section?

Thanks

**Comment by bahmutov** [comment]
you are right in general case (like if the tool is found). But for errors, showing helpful message right away is a must I think

**Comment by satazor** [comment]
I’m building a CLI tool where I use bin-up but I also have a fallback. It’s weird for users to see those erros printed in the console while stuff works..

**Comment by bahmutov** [comment]
Oh I see, so you need actual module API from this?

**Comment by ctrlplusb** [comment]
Super keen on not seeing the "Found..." logs. I run your script at the bootstrap of every test suite within my application. Getting quite a lot of output.

Would you consider wrapping the informational console.log statements with a `if (process.env.VERBOSE) {` check?

**Comment by ctrlplusb** [comment]
Wow! Quick response, thanks ❤️
